# Generated by Django 2.1.3 on 2018-12-02 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('username', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='User')),
                ('token', models.CharField(max_length=250, verbose_name='Token')),
            ],
        ),
    ]
